#!/bin/zsh

setopt +o nomatch

# purge .DS_Store files and other crap
rm -rf **/._*
rm -rf **/.DS_Store
rm -rf **/__MACOSX
rm -rf **/\~\$*
rm -rf **/*.dSYM

# non-macos but this crap tends to get dissipated
rm -rf **/__pycache__
rm -rf **/a.out
rm -rf **/*.o

# git crap
rm -rf **/*.orig
rm -rf **/*.rej

