#!/bin/bash

window=$(xdotool getactivewindow)

set -- junk $(cat ~/.cache/emoji | cut -d '|' -f 1 | dmenu -p emoji)

shift

if [ $# -eq 0 ]; then
    exit
fi

emoji=$(cat ~/.cache/emoji | grep "^$(echo $@)|" | cut -d '|' -f 2 | tr -s '\r')

echo "$emoji" | xclip -selection clipboard

xdotool windowactivate $window

