#!/bin/bash

#
# jcp
# Copy files in and out of jail.
#

filepath=$(realpath "$1")
rootdir=$(echo "$filepath" | cut -d "/" -f2)
if [ "$rootdir" == "jail" ];
then
	cp "$filepath" "/$(echo "$filepath" | cut -d "/" -f3-)"
else
	cp "$(pwd)/$1" "/jail/$(pwd)/$1"
fi

