#!/bin/sh

# download and synchronise email accounts
mbsync -c "$HOME/.config/mbsync/mbsyncrc" -a

if [ "$?" != 0 ];
then
	exit # sync failed
fi

folder_blacklist="Drafts Rubbish Sent Spam cur new tmp"

# count number of new messages
total_new=0
for account in "$HOME/Mail/*";
do
	mailboxes="$account/* $account/INBOX/*"
	for mailbox in $mailboxes;
	do
		basebox="$(basename $mailbox)"
		case "$folder_blacklist" in
			*"$basebox"*)
				# in the blacklist - ignore
				;;
			*)
				# count the new messages
				num_new=$(ls $mailbox/new | wc -l)
				total_new=$(expr $total_new + $num_new)
				;;
		esac
	done
done

icon="$HOME/.config/dunst/icons/mail.png"

if [ "$total_new" == 0 ];
then
	dunstify -r 10000006 -u normal -i "$icon" "Mail synchronised" "No new messages."
elif [ "$total_new" == 1 ];
then
	dunstify -r 10000006 -u normal -i "$icon" "Mail synchronised" "1 new message."
else
	dunstify -r 10000006 -u normal -i "$icon" "Mail synchronised" "$total_new new messages."
fi

