#!/bin/sh

# toggle touchpad

icon="$HOME/.config/dunst/touchpad.png"

if [ "$(cat ~/.config/x/tpenable)" -eq 0 ];
then
	mode=1
	echo $mode > ~/.config/x/tpenable
	dunstify -r 10000008 -u normal -i "$icon" "Touchpad" "Enabled"
else
	mode=0
	echo $mode > ~/.config/x/tpenable
	dunstify -r 10000008 -u normal -i "$icon" "Touchpad" "Disabled"
fi
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" $mode

