#!/bin/sh

help() {
	echo "update [option]"
	echo "    help          - show this message"
	echo "    sync          - synchronise local database with server"
	echo "    fetch         - download update tarballs from server"
	echo "    install       - install updates"
	echo "    clean         - clean up local database"
}

if [ -z "$1" ];
then
	help
	exit 0
fi

if [ -x $(command -v lsb_release) ];
then
	echo "Missing command lsb_release! Please consider installing it."
	echo "Will attempt to detect package manager manually..."
	if [ -x $(command -v apt) ];
	then
		distro="Debian"
		echo "Found 'apt' package manager."
	elif [ -x $(command -v emerge) ];
	then
		distro="Gentoo"
		echo "Found 'emerge' package manager."
	else
		echo "Could not find a valid package manager! Quitting..."
		exit 1
	fi
else
distro="$(lsb_release -i | awk '{print $3}')"
fi

whoami="$(whoami)"
privrun() {
	if [ "$whoami" = "root" ];
	then
		$@
	else
		sudo $@
	fi
}

sync() {
	case "$distro" in
	Debian)
		privrun apt update
		;;
	Gentoo)
		privrun emerge --sync
		;;
	*)
		echo "Unrecognised distribution '$distro'!"
		exit 1
		;;
	esac
}

fetch() {
	case "$distro" in
	Debian)
		privrun apt upgrade --download-only
		;;
	Gentoo)
		privrun emerge -auDNqvf --with-bdeps=y @world
		;;
	*)
		echo "Unrecognised distribution '$distro'!"
		exit 1
		;;
	esac
}

install() {
	case "$distro" in
	Debian)
		privrun apt upgrade
		;;
	Gentoo)
		privrun emerge -auDNqv --with-bdeps=y @world
		;;
	*)
		echo "Unrecognised distribution '$distro'!"
		exit 1
		;;
	esac
}

clean() {
	case "$distro" in
	Debian)
		privrun apt autoremove --purge
		;;
	Gentoo)
		privrun emerge -ac
		;;
	*)
		echo "Unrecognised distribution '$distro'!"
		exit 1
		;;
	esac
}

# parse arguments
case "$1" in
	sync)	sync ;;
	fetch)	fetch  ;;
	install) install ;;
	clean) clean ;;
	help|*) help  ;;
esac

