#!/bin/sh

# show connections and addresses
module_internet() {
	for ethdev in "/sys/class/net/e*";
	do
		eth="$(sed "s/down//;s/up/ETH/" "$ethdev/operstate")"
		if [ -n "${eth}" ];
		then
			ethspeed=$(cat "$ethdev/speed")
			echo "$eth ($ethspeed)"
		fi
	done

	wifi="$(grep "^\s*w" /proc/net/wireless | awk '{ print "WIFI", int($3 * 100 / 70) "%" }')"
	if [ -n "${wifi}" ];
	then
		echo "$wifi"
	fi
	if [ -n "${wifi}${eth}" ];
	then
		ip route get 1 | awk '{print $7;exit}'
		#hostname -i | cut -d' ' -f1
	else
		echo "NET OFF"
	fi
}

module_disk() {
	echo $(df -h --total | tail -n1 | awk -vOFS='/' '{ print $3, $2 }')
}

while true;
do
	module_internet > "$HOME/.config/status/internet"
	module_disk > "$HOME/.config/status/disk"
	dwmbar
	sleep 30
done

